# AWS S3 Configuration
aws.region=${AWS_REGION:us-east-2}
aws.s3.bucket.name=${AWS_S3_BUCKET_NAME:ani-pruebas}
aws.s3.file.name=${AWS_S3_FILE_NAME:archivos-prueba.csv}
aws.s3.default.prefix=${AWS_S3_DEFAULT_PREFIX:archivo/}
aws.s3.output.prefix=${AWS_S3_OUTPUT_PREFIX:output/}

# File Division Configuration
file.division.expected.records=${EXPECTED_RECORDS:1000000}
file.division.records.per.chunk=${RECORDS_PER_CHUNK:10000}

# Quarkus S3 Configuration
quarkus.s3.aws.region=${AWS_REGION:us-east-2}
quarkus.s3.aws.credentials.type=default

# Lambda Configuration
quarkus.lambda.handler=get
quarkus.package.jar.type=legacy-jar


